 
Skip = ["Skip","skip"]
if input not in Skip:
    print ("INPUT SKIP IF YOU WANT TO GO BACK")
    print ("There was a place called the Gods Foundry in which all the gods were made and the powers was forged")
    input("Continue")
    print ("The other gods conspired against one god in particular called shadow man. They feared he would go rogue")
    input("Continue")
    print ("They all fought and banished him allowing him to create a new realm called the SHADOW REALM")
    input("Continue")
    print ("He would use this realm to plan an attack from the inside and create a backdoor to invade the universe to kill the gods")
    input("Continue")
    print ("He chose a man named Andy and invaded his mind giving him nightmares of a more powerful version of him from another universe that woudld attempt to kill him")
    input("Continue")
    print ("Shadow Man broke Andy to the point he could enter his mind and allow him to travel the multiverse and give him the ability to absorb the power of his variants to grow stonger")
    input("Continue")
    print ("By creating these connections to his different variants in his nightmares he seeked out all his variants to become the one true andy with a galactic amount of power")
    input("Continue")
    print ("By travelling the multiverse, cracks was left from where he entered. Without the cracks being healed they grew allowing the barriers between universes to collapse")
    input("Continue")
    print ("Shadow Man could now reach through the multiverse because of andy and began to expand the shadow realm")
    input("Continue")
    print ("He grabbed beings from different universes and put them on the planet earth")
    input("Continue")
    print ("The narrator had a plan to stop and created THE PLAYER as a puppet to control the mind of to discover what was going on")
    input("Continue")
    print ("The narrator gathered the information from his created spy and sent it to the gods")
    input("Continue") 
    print ("They answered and teamed up to put an end to shadow man")
    input("Continue")
    print ("However the chaos was too much as wars began to happen leading to the ORB OF ALL being destroyed")
    input("Continue")
    print ("The ORB OF ALL contained the Creator 'ALL', who was responsible for the creation of ALL universes")
    input("Continue")
    print ("ALL created and controlled the barriers between the universes to avoid any universal wars from happening")
    input("Continue")
    print ("But he gave up a lot of his energy and life by creating life and so as his last creation he created his daughter, the ALL-KNOWING, GOD OF KNOWLEDGE AND MIND")
    input("Continue")
    print ("OBSERVATION MAN accidentally blew up the ORB OF ALL by firing a laser through a train exploding the train which therefore destroyed the ORB OF ALL")
    input("Continue")
    print ("ALL barriers between universes vanished and so a lot of wars and a lot of death broke out")
    input("Continue")
    print ("The first war happened and this is when ALL-KNOWING decided enough is enough")
    input("Continue")
    print ("The ALL-KNOWING collected all the souls from the war and used this to destroy shadow man")
    input("Continue")
    print ("That was until the NARRATOR volunteered to absorb all the stars,souls,planets and reset the world which would extinguish him in the process")
    input("Continue")
    print ("ALL-KNOWING knew this was the better option and gave the go ahead. She knew this would mean all the universes would become one and allow for travel between but would also mean they would have a chance to prepare")
    input("Continue")
    print ("The biggest bang happened which resulted in the wiping of all universes to create another with all of them together as one")
    input("Continue")
    print ("This would release the world hidden by the gods. The NEW WORLD")
    input("Continue")
    print ("The world were the gods rest or are banished to")
    input("Continue")
    print ("The gods use the stars and meteors to create a barrier around it so that if the barrier collapses then so does this world")
    input("Continue")
    print ("Now you are here to play the game so lets get to it.")

import Game
